customhost = "employee.ck9hfqcyv0yw.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "toosweewah-employee"
customregion = "us-east-1"
