customhost = "employee.cpzk4cq9m9x4.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "foojiaqi-employee"
customregion = "us-east-1"
